name: womenshealth
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-120.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.2
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1
#  flutter_launcher_name: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Set launcher name: https://pub.dev/packages/flutter_launcher_name
flutter_launcher_name:
  name: 'Healthy Women'

# Generate app icons: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path_ios: 'assets/images/tampon.png'
  image_path_android: 'assets/images/tampon.png'

# Generate splash screens: https://pub.dev/packages/flutter_native_splash
flutter_native_splash:
  color: '#ececec'
  image: 'assets/images/tampon.png'

